openapi: 3.0.3
info:
  title: Products Service API
  version: 1.0.11
servers:
  - url: https://0whhlv5ewj.execute-api.us-east-1.amazonaws.com/prod
tags:
  - name: products
paths:
  /products:
    get:
      tags:
        - products
      summary: Get list of products
      responses:
        "200":
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: No products found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No products found"
    post:
      tags:
        - products
      summary: Create a product
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Product title"
                description:
                  type: string
                  example: "Product description"
                count:
                  type: number
                  format: int
                  example: 5
                price:
                  type: number
                  format: float
                  example: 256.34
      responses:
        "200":
          description: A product is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product 0baf3369-5b10-4bab-8305-e8ec1d60e3ad is sucessfully added"
        "400":
          description: A product creation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "A product creation failed"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

  /products/{id}:
    get:
      tags:
        - products
      summary: Find product by ID
      description: Returns a single product
      parameters:
        - name: id
          in: path
          description: ID of the product
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A product
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product not found"
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "Product 1"
        description:
          type: string
          example: "Product 1 description"
        count:
          type: number
          format: int
          example: 5
        price:
          type: number
          format: float
          example: 256.34
